variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  image: golang:stretch
  script:
    - /bin/sh build.sh
  artifacts:
    paths:
      - artifacts/*
    expire_in: 8 weeks
